manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/cody-shearer
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: init
      import: app/west.yml
  self:
    path: config
