manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/cody-shearer
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: delay-hold-on-interrupt
      import: app/west.yml
  self:
    path: config
